version: '3'

services:
  openjdk:
    image: openjdk:17.0.2-oraclelinux8
    restart: unless-stopped
    volumes:
      - "./data/application.jar:/application.jar"
    environment:
      - JAVA_OPTS=""      
    ports:
      - "82:82"
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -jar /application.jar" ]
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"